default:
  appName: "readmycards"
  port: 3000
  environment: "local"
  apikey: "8a6c3dc6-3d62-4f6a-a01f-8243528738ee"
  gcloud:
    project: "t1t-infrastructure"
    keyfile: "config/keyfile.json"
  mailgun:
    scheme: "https"
    url: "api.mailgun.net/v3/saas.t1t.be/messages"
    user: "api"
    apikey: "key-df014f8e692c21125509e0ae72c97b69"
    sender: "\"ReadMyCards.eu\" <noreply@saas.t1t.be>"