default:
  appName: "readmycards"
  port: 3000
  environment: "local"
  redirect:
    scheme: "http"
    domain: "localhost"
    port: 3000
  auth:
    uri: "https://accapim.t1t.be"
    path: "/apiengineauth/v1"
    apikey: "<api key>"
  cloudconvert:
    apikey: "<cloudconvert api key>"
  gcloud:
    project: "<gcloud project name>"
    keyfile: "<keyfile path>"
  mailgun:
    scheme: "https"
    url: "api.mailgun.net/v3/saas.t1t.be/messages"
    user: "<mailgun api user>"
    apikey: "<mailgun api key>"
    sender: "\"ReadMyCards.eu\" <noreply@saas.t1t.be>"
  signbox:
    uri: "<api manager uri>"
    path: "<signbox basepath>"
    apikey: "<api key>"
    division_id: <divisionId to use>
    workflow_id: <workflowId to use>
    role: "<role name to use>"

test:
  appName: "readmycards"
  scheme: "http"
  domain: "localhost"
  port: 3001
  environment: "TEST"
  redirect:
    scheme: "http"
    domain: "localhost"
    port: 3001