default:
  appName: "readmycards"
  port: 3000
  environment: "local"
  apikey: "<your apikey>"
  gcloud:
    project: "<gcloud project name>"
    keyfile: "<keyfile path>"
  mailgun:
    scheme: "https"
    url: "api.mailgun.net/v3/saas.t1t.be/messages"
    user: "<mailgun api user>"
    apikey: "<mailgun api key>"
    sender: "\"ReadMyCards.eu\" <noreply@saas.t1t.be>"